# Generated by Django 3.2 on 2022-10-13 18:35

import json
from django.contrib.gis.geos import fromstr
from pathlib import Path
from .models import Hospitals


hospitals_json =Path(__file__).resolve().parent / 'data' / 'export_hopital.json'
def run():
            jsonfile = hospitals_json

            with open(str(jsonfile)) as datafile:
                objects = json.load(datafile)
                for obj in objects['elements']:
                    try:
                        objType = obj['type']
                        if objType == 'node':
                            tags = obj['tags']
                            name = tags.get('name','no-name')
                            city = tags.get('city','no-city')
                            street = tags.get('address','no-address')
                            contact_phone = tags.get('contact_phone','no-contact_phone')
                            longitude = obj.get('lon', 0)
                            latitude = obj.get('lat', 0)
                            location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                            Hospitals(name=name, location = location, city=city, street=street, contact_phone =contact_phone).save()
                    except KeyError:
                        pass 
            




        
