# Generated by Django 3.2 on 2022-10-14 08:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('city', models.CharField(blank=True, db_column='addr:city', max_length=255, null=True)),
                ('street', models.CharField(blank=True, db_column='addr:street', max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, db_column='contact:phone', max_length=255, null=True)),
            ],
            options={
                'db_table': 'hospitals',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('name_zone', models.CharField(blank=True, max_length=50, null=True)),
                ('id_zone', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'zones',
                'managed': True,
            },
        ),
    ]
